### PR TITLE
Ticket master api

### PR DESCRIPTION
**Pull request by TylerCarpenter92**
finished fetch request and added drop down to html for concert section

### CODE REVIEW

**Comment by dkrusch** [comment]
The array grows every time the button is clicked, probably something to do with where the array is declared.

**Comment by TylerCarpenter92** [comment]
i fixed the problems i had and updated my branch. still need to refactor my api file so i will probably update this branch again.

**Comment by shanemiller89** [comment]
:+1:

**Comment by dkrusch** [comment]
👍

**Comment by joekennerly** [comment]
I 'think' it works 👍

**Pull request merged**
